### PR TITLE
📽 transitions init

### PR DESCRIPTION
**Pull request by albinotonnina**
Great work Sara!
I took the chance to explore Vue for the first time, thanks to you. I like Vue! :)
This little PR is about the transition you used for the code.
IMHO very cool at the beginning, a little tiny bit too long to wait for after the second/third method change.
I had the feeling of wanting those character to finish typing out sooner just to read the snippet.
I like, for UX purposes mostly, to always keep the animation smaller (http://valhead.com/2016/05/05/how-fast-should-your-ui-animations-be)

Well I propose a change in the animation library (https://github.com/juliangarnier/anime) instead of gsap. I personally found it lightweight and close enough to the metal!
Then I propose a different animation. A little elasticky if you want :)

### CODE REVIEW

**Comment by sdras** [comment]
Hi, thanks for stopping by! No thank you, I like this animation and GreenSock.

**Comment by albinotonnina** [comment]
Ok, thanks!

**Comment by sdras** [comment]
Do you know that Val and I teach this content together? If you're interested, we give workshops. Anime and GreenSock work the same under the hood, by the way.

Thanks!

**Comment by albinotonnina** [comment]
@sdras oh I would be surprised if someone doesn't know about your collaboration!
I never explored the internals of greensock stuff although I've been using it since gsap for flash in the nineties..oh my.
Well my version is saving 100kb to the final dist but considering the target we are not talking about too much I suppose. Also I liked what Val said. I'm also aware of the many principles for good UX transitions (material, 12 disney principles and similar interesting resources). I like to live by them in my daily coding :)
Thank you for the invitation, luckily I'm in London so I have many occasions to see you people often!

**Comment by sdras** [comment]
It would be hard to save 100kb to the final dist as GSAP weighs a fraction of that gzipped minified in total ;)

**Comment by albinotonnina** [comment]
@sdras my bad, gzip not considered eheheh.
Anyway, now we are talking 48531 bytes (anime) vs 80424 bytes (greensock)
Please notice I'm not defending anime, it really does not matter the difference in bytes compared to the features and the dx 😄

**Comment by sdras** [comment]
The testing link goes to an empty page. It also matters what order to run things in for minification and gzipping. Either way, I thank you for your time here but GreenSock has a lot of other features that I'm interested in. Best wishes.

**Comment by albinotonnina** [comment]
You know what, I think I still have some unjustified reserve against greensock, I think for license issues that may have occurred years and years ago and probably when I was writing actionscript!
A negative bias that should definitely be resolved. At least this episode made me more aware of the issue and I'll consider it more in the future. 
Best wishes

**Comment by sdras** [comment]
Totally fine, we all have our biases :) Thanks for revisiting it, that takes a lot of maturity.

**Pull request closed without merging**
