### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by Ashugeo**
Hi! I think your tools for arrays and objects exploring are very useful and just thought I'd give a hand for this french translation. Let's discuss it here!

### CODE REVIEW

**Comment by sdras** [comment]
Hi @Ashugeo, thanks for your help! There are actually a few more things that need to be done to create a full translation. Can you please head over to CONTRIBUTING.md, there's a section on Translations there :) Thanks!

**Comment by sdras** [comment]
@mmnlfrrr had expressed interest in creating a French translation in #1, perhaps you two can collaborate?

**Comment by Ashugeo** [comment]
Yeah I just saw #1, sorry, should have looked up there first! @mmnlfrrr feel free to ping me if you started translating in french as well. 🙂 

Also I'm working on the files in /store right now.

**Comment by Ashugeo** [comment]
@sdras I'm done. Maybe @mmnlfrrr would you like to review my translation and credit yourself when it's done? I may have left some typos, and I guess some sentences can be improved.

**Comment by sdras** [comment]
I love that, I'll leave it open for a day and then just merge it in if we haven't heard back. THANK YOU!

**Comment by mmnlfrrr** [comment]
@Ashugeo  was faster than me. I will do a relecture to see if there are errors

**Comment by sdras** [comment]
Thank you both!

**Pull request merged**
